display = "27things"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://27things.net/"
title = "27things"
years = [ 2008 ]
