display = "86’s world"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.syx86.cn/"
title = "86’s world"
years = [ 2008 ]
