display = "AA39空间"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.aa39.com/"
title = "AA39空间"
years = [ 2009 ]
