display = "Aaron"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.beatledork.com/"
title = "Aaron"
years = [ 2006 ]

[[websites]]
url   = "https://web.archive.org/web/http://www.aaronwang.cn/"
title = "Aaron"
years = [ 2009 ]
