display = "Ada Hsu 的胡思亂想"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.adahsu.net/ada/space/start"
title = "Ada Hsu 的胡思亂想"
years = [ 2008 ]
