display = "Adam Wilcox’s WilcosWorld"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://wilcosworld.co.uk/"
title = "Adam Wilcox’s WilcosWorld"
years = [ 2008 ]
