display = "Adame"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://adame.pfwh.net/"
title = "Adame"
years = [ 2006 ]
