display = "Adrian"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.sirharris.com/"
title = "Adrian"
years = [ 2006 ]

