display = "aeli.cho"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://theboy.tistory.com/"
title = "aeli.cho"
years = [ 2008 ]
