display = "Aenimablog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://aperfectcircle.hu/blog"
title = "Aenimablog"
years = [ 2007 ]
