display = "Aguillem-creations [Le Blog]"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "http://web.archive.org/web/20071214103537/http://blog.aguillem-creations.fr:80/"
title = "Aguillem-creations [Le Blog]"
years = [ 2007 ]
