display = "Akachanwear Baby Store"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://jp.akachanwear.com/"
title = "Akachanwear Baby Store"
years = [ 2008 ]
