display = "All Things…Photography"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://thomdurfee.com/"
title = "All Things…Photography"
years = [ 2008 ]
