display = "Allan Haggett"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://journal.allanh.org/"
title = "Allan Haggett"
years = [ 2006 ]
