display = "Alpongson’s Blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://alponglog.com/"
title = "Alpongson’s Blog"
years = [ 2008 ]
