display = "Aluan（阿栾）"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://aluan.org/blog"
title = "Aluan（阿栾）"
years = [ 2009 ]
