display = "Anthony Ettinger"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.chovy.com/"
title = "Anthony Ettinger"
years = [ 2006 ]
