display = "apparently.me.uk"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.apparently.me.uk/"
title = "apparently.me.uk"
years = [ 2007 ]
