display = "araba"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.arabalife.com/"
title = "araba"
years = [ 2008 ]
