display = "ArdeSolo"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.ardesolo.net/"
title = "ArdeSolo"
years = [ 2007 ]
