display = "Ari Prakash"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://ari.foo/"
title = "Ari Prakash"
years = [ 2026, 2025 ]
