display = "Ariyako ' Najib Palace"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.ariyako.org/"
title = "Ariyako &#39; Najib Palace"
years = [ 2008 ]
