display = "auduns.no"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.auduns.no/"
title = "auduns.no"
years = [ 2007 ]

[[websites]]
url   = "https://web.archive.org/web/2007/http://auduns.no/"
title = "Auduns.no"
years = [ 2008 ]
