display = "ayt web dizayn"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://aytwebdizayn.net76.net/"
title = "ayt web dizayn"
years = [ 2008 ]
