display = "Bald Man Blogging"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.baldmanblogging.com"
title = "Bald Man Blogging"
years = [ 2008 ]
