display = "Becky"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.babblative.com/"
title = "Becky"
years = [ 2006 ]
