display = "Better Web Posse"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.betterwebposse.com/"
title = "Better Web Posse"
years = [ 2008 ]
