display = "Beyazblog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.beyazblog.com/"
title = "Beyazblog"
years = [ 2007 ]
