display = "blacktulip"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blacktulip.cn/"
title = "blacktulip"
years = [ 2008 ]
