display = "Blog do Markun"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://blog.markun.com.br/"
title = "Blog do Markun"
years = [ 2008 ]
