display = "blog.the-kid.org"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.the-kid.org/"
title = "blog.the-kid.org"
years = [ 2008 ]
