display = "bluenlive"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://bluenlive.net/"
title = "bluenlive"
years = [ 2008 ]
