display = "BoldEagle"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://boldeagle.org/"
title = "BoldEagle"
years = [ 2007 ]
