display = "Brendan"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://incoherently.net/"
title = "Brendan"
years = [ 2006 ]
