display = "Brian Talbot"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.brian-talbot.com/portfolio"
title = "Brian Talbot"
years = [ 2008 ]
