display = "Britannia Pool League"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://britannia-pool.org/"
title = "Britannia Pool League"
years = [ 2007 ]
