display = "Brooker Fanatics"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.brookerfanatics.com/"
title = "Brooker Fanatics"
years = [ 2008 ]
