display = "bzugodesign.com"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.bzugodesign.com/"
title = "bzugodesign.com"
years = [ 2008 ]
