display = "Ceдьmoй Сайт"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://7thsite.ru/"
title = "Ceдьmoй Сайт"
years = [ 2008 ]
