display = "Cédric Bonvin"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.visionlibre.net/"
title = "Cédric Bonvin"
years = [ 2006 ]
