display = "Ceglie Messapica"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "http://www.ceglieplurale.it/"
title = "Ceglie Plurale"
years = [
	2007,
	2008 
]

[[websites]]
url   = "http://web.archive.org/web/20081231020253/http://blog.cegliemessapica.com:80/"
title = "Blog"
years = [ 2008 ]
