display = "Chalk is Cheap"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "http://web.archive.org/web/20080329065808/http://chalkischeap.co.za:80/"
title = "Chalk is Cheap"
years = [ 2008 ]
