display = "Charlie Griefer"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://charlie.griefer.com/"
title = "Charlie Griefer"
years = [ 2009 ]
