display = "cledison.com web blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://cledison.com/"
title = "cledison.com web blog"
years = [ 2007 ]
