display = "ClubEddy.com"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.clubeddy.com/"
title = "ClubEddy.com"
years = [ 2008 ]
