display = "Conficker"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://conficker.com/"
title = "Conficker"
years = [ 2009 ]
