display = "Conscious Geek"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.consciousgeek.com/"
title = "Conscious Geek"
years = [ 2007 ]
