display = "Cookieface"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.cookieface.com.ar/"
title = "Cookieface"
years = [ 2008 ]
