display = "CSS Page"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://www.csspage.com/"
title = "CSS Page"
years = [ 2009 ]
