display = "CVJM Nürnberg"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.cvjm-nuernberg.de/"
title = "CVJM Nürnberg"
years = [ 2009 ]
