display = "D and V"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.dimlau.com/"
title = "D and V"
years = [ 2007 ]
