display = "dam-dam"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.dam-dam.de/"
title = "dam-dam"
years = [ 2009 ]
