display = "Dan Bowling"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.northlander.org/"
title = "Dan Bowling"
years = [ 2006 ]
