display = "Dan Catt’s GeoBloggers"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.geobloggers.com/"
title = "Dan Catt’s GeoBloggers"
years = [ 2007 ]
