display = "Dave Marks"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.dave-marks.co.uk/"
title = "Dave Marks"
years = [ 2007 ]
