display = "Dave Pitalo"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://www.davepitalo.com/blog"
years = [ 2006 ]
