display = "DED|Chain"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://dedchain.dustindiaz.com/"
title = "DED|Chain"
years = [ 2007 ]
