display = "Designer&Developer"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.chris-wallace.com/"
title = "Designer&amp;Developer"
years = [ 2009 ]
