display = "/dev/work"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.devwork.org/"
title = "/dev/work"
years = [ 2008 ]
