display = "Dezzanet"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.dezzanet.co.uk/"
title = "Dezzanet"
years = [
	2008,
	2009 
]
