display = "Dianso’s Blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://014.cc/"
title = "Dianso’s Blog"
years = [
	2008,
	2009 
]
