display = "Dig Digger"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://digdigger.xail.net/"
title = "Dig Digger"
years = [ 2006 ]
