display = "Digamber"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.d313k.com/"
title = "Digamber"
years = [ 2009 ]
