display = "Digicted"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://digicted.nl/"
title = "Digicted"
years = [ 2007 ]
