display = "Dimo Dimov web"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.dimodi.com/"
title = "Dimo Dimov web"
years = [ 2007 ]
