display = "diversiya"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://atrada.ru/"
title = "diversiya"
years = [ 2008 ]
