display = "Dizi Designs"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://dizidesigns.co.uk/"
title = "Dizi Designs"
years = [ 2009 ]
