display = "DotNetWizard"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://dotnetwizard.net/"
title = "DotNetWizard"
years = [ 2008 ]
