display = "Dreamhost promo"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.dreamhost-promo-code.net/"
title = "Dreamhost promo"
years = [ 2008 ]
