display = "Dreadnaut"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://dreadnaut.altervista.org/"
title = "Dreadnaut"
years = [ 2006 ]
