display = "DSNG blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.dsng.hu/"
title = "DSNG blog"
years = [ 2008 ]
