display = "Due Chiacchiere"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://duechiacchiere.it/"
title = "Due Chiacchiere"
years = [
	2006,
	2007,
	2008,
	2022,
	2023,
	2024,
	2025,
	2026
]
