display = "e-dentity"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://mpsandoval.com"
title = "e-dentity"
years = [ 2007 ]
