display = "Ebo"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.pocastella.com/ebo"
title = "Ebo"
years = [ 2006 ]
