display = "Ed"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.duhhed.com/"
title = "Ed"
years = [ 2006 ]
