display = "EDO-DESIGN Studio"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.edo-design.com/"
title = "EDO-DESIGN Studio"
years = [ 2008 ]
