display = "El Peor Blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.elpeorblog.com/"
title = "El Peor Blog"
years = [ 2007 ]
