display = "Elfen Lied"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://my-elfen-lied.ru/"
title = "Elfen Lied"
years = [ 2009 ]
