display = "Elinity web design"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.elinity.com/"
title = "Elinity web design"
years = [ 2008 ]
