display = "Ellos"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.deals.se/"
title = "Ellos"
years = [ 2008 ]
