display = "entertainer"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.entertainer.vhost.lt/wp/"
title = "entertainer"
years = [ 2007 ]
