display = "eoonk.de"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.roonk.de/228-titten-die-zweite.html"
title = "eoonk.de"
years = [ 2008 ]
