display = "Erolando"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.erolando.net/"
title = "Erolando"
years = [ 2006 ]
