display = "esernyoscsiga"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://esernyoscsiga.13wings.net/"
title = "esernyoscsiga"
years = [ 2008 ]
