display = "Euforia – Categorical Ideal"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://euforia.tistory.com/"
title = "Euforia – Categorical Ideal"
years = [ 2008 ]
