display = "evo73"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.evo73.org"
title = "evo73"
years = [ 2008 ]
