display = "eyePIXELS"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://makkistudios.com/"
title = "eyePIXELS"
years = [ 2007 ]
