display = "Fabien Lasserre"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2019/https://www.primative.net"
title = "Fabien Lasserre"
years = [ 2020 ]
