display = "Faceit"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.faceit.se/"
title = "Faceit"
years = [ 2007 ]
