display = "fasnet-musix.de"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.fasnet-musix.de/"
title = "fasnet-musix.de"
years = [ 2008 ]
