display = "Fearhsonic"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://www.fearhsonic.com/"
title = "Fearhsonic"
years = [ 2009 ]
