display = "felipediesel.net"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://felipediesel.net/"
title = "felipediesel.net"
years = [ 2007 ]
