display = "Ferenc Veres"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://lion.xaraya.hu/"
title = "Ferenc Veres"
years = [ 2009 ]
