display = "Finance site"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.loancalculatorusa.com/"
title = "Finance site"
years = [ 2009 ]
