display = "flex.fleximus.de"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://flex.fleximus.de/"
title = "flex.fleximus.de"
years = [ 2008 ]
