display = "Florian"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://malerama.de/"
title = "Florian"
years = [ 2006 ]
