display = "Flysmart"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://flysmart.info/"
title = "Flysmart"
years = [ 2008 ]
