display = "freezone web design"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.3zone.it/"
title = "freezone web design"
years = [ 2007 ]
