display = "Frontend Dogma"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://frontenddogma.com/"
title = "Frontend Dogma"
years = [
	2022,
	2023,
	2024,
	2025,
	2026,
]

# Accounts
# ------------------------------------------------------------------------------

[[accounts]]
type = "Mastodon"
url  = "https://mas.to/@frontenddogma"

[[accounts]]
type     = "GitHub"
url      = "https://github.com/frontenddogma"
