display = "FTC SPbSPU"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://ftk.spbstu.ru/"
title = "FTC SPbSPU"
years = [ 2007 ]
