display = "Gift and Present"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.lovercorner.com/"
title = "Gift and Present"
years = [ 2008 ]
