display = "gmachina"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://gmachina.com/"
title = "gmachina"
years = [ 2008 ]
