display = "Gmpr"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.givemepagerank.com/"
title = "Gmpr"
years = [ 2007 ]
