display = "GO! FLAViEN"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://blog.fsw.org.cn/"
title = "GO! FLAViEN"
years = [ 2007 ]
