display = "good.xf.cz"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.good.xf.cz/"
title = "good.xf.cz"
years = [ 2007 ]
