display = "Googlisti"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://googlisti.com/"
title = "Googlisti"
years = [
	2006,
	2007 
]
