display = "Great Maddrin!"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.greatmaddrin.com"
title = "Great Maddrin!"
years = [ 2007 ]
