display = "Greengnn"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.jluvip.com/blog"
title = "Greengnn"
years = [ 2006 ]
