display = "Grey Fox"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://hacktek.net/"
title = "Grey Fox"
years = [ 2006 ]
