display = "Grzesiek"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://granatowysen.net/"
title = "Grzesiek"
years = [ 2006 ]
