display = "…Gurgi.Girl"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.gurgi-girl.net/"
title = "…Gurgi.Girl"
years = [ 2008 ]
