display = "Gutscheinbunker"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.gutscheinbunker.de/"
title = "Gutscheinbunker"
years = [ 2008 ]
