display = "Happy Pixels"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://happypixels.net/"
title = "Happy Pixels"
years = [ 2009 ]
