display = "HASENFARM – Das Leben ist schön"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.hasen-farm.de/"
title = "HASENFARM – Das Leben ist schön"
years = [ 2008 ]
