display = "Henrietta@Sunshine State"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.ettachou.com/"
title = "Henrietta@Sunshine State"
years = [ 2008 ]
