display = "Hop Talk"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://hop-talk.com/"
title = "Hop Talk"
years = [ 2008 ]
