display = "Huiju’s weblog : jugug.net"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://jugug.net/"
title = "Huiju’s weblog : jugug.net"
years = [ 2008 ]
