display = "Hyuk Hur"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://blog.hyukhur.com/"
title = "Hyuk Hur"
years = [ 2009 ]
