display = "imamomdealwithit"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.imamomdealwithit.com/"
title = "imamomdealwithit"
years = [ 2008 ]
