display = "Индустриальные парки"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://industrial-park.ru"
title = "Индустриальные парки"
years = [ 2009 ]
