display = "Invisible Window"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.invisiblewindow.com/notepad"
title = "Invisible Window"
years = [ 2007 ]
