display = "iStylr – Online Tableless CSS Generator"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://istylr.com/"
title = "iStylr – Online Tableless CSS Generator"
years = [ 2008 ]
