display = "IVershuo’s Blog (Beta)"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://beta.ivershuo.cn/"
title = "IVershuo’s Blog (Beta)"
years = [ 2009 ]
