display = "Jack Mottram"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://submitresponse.co.uk/mt/"
title = "Jack Mottram"
years = [ 2006 ]
