display = "jai"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.jailal.com"
title = "jai"
years = [ 2008 ]
