display = "James Angus"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.ucantblamem.com/"
title = "James Angus"
years = [ 2007 ]
