display = "Jászbróker"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://jaszbroker.hu/"
title = "Jászbróker"
years = [ 2008 ]
