display = "Jen"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.jayesel.net/"
title = "Jen"
years = [ 2006 ]
