display = "JennaJones.com"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.jennajones.com/"
title = "JennaJones.com"
years = [ 2008 ]
