display = "Jeremy Flint"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.jeremyflint.com/"
title = "Jeremy Flint"
years = [ 2006 ]
