display = "Jidah Hamidy"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.jiduh,com"
title = "Jidah Hamidy"
years = [ 2009 ]
