display = "Joern"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://immaterialfacts.com/"
title = "Joern"
years = [ 2006 ]
