display = "Johna"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://action.nu/johna"
title = "Johna"
years = [ 2006 ]
