display = "John Havlik"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://mtekk.weblogs.us/"
title = "John Havlik"
years = [
	2006,
	2007,
	2008 
]
