display = "Jon Carico"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://joncarico.com/"
title = "Jon Carico"
years = [ 2007 ]
