display = "Jordi Pujalte"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://loc.abses.com/"
title = "Jordi Pujalte"
years = [ 2006 ]
