display = "José Moreno"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://josemoreno.com.uy/"
title = "José Moreno"
years = [ 2009 ]
