display = "Joseph Hinson"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://geekitopia.com/"
title = "Joseph Hinson"
years = [ 2009 ]
