display = "journal from STRUND"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://journal.strund.jp/"
title = "journal from STRUND"
years = [ 2008 ]
