display = "kabturek"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "http://web.archive.org/web/20081015213252/http://tumble.kabturek.info/"
title = "kabturek"
years = [ 2008 ]
