display = "Karailiev.net"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://karailiev.net/"
title = "Karailiev.net"
years = [ 2008 ]
