display = "KennethSeals.com"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.kennethseals.com/"
title = "KennethSeals.com"
years = [ 2007 ]
