display = "Kevindesign"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://kevindesign.se/"
title = "Kevindesign"
years = [ 2007 ]
