display = "khairilz"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://khairilz.speakerz.net/"
title = "khairilz"
years = [ 2007 ]
