display = "Krazy Kory"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://krazykory.com/"
title = "Krazy Kory"
years = [ 2007 ]
