display = "Kretyn cytaty"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.kretyn.com/"
title = "Kretyn cytaty"
years = [ 2007 ]
