display = "kunshou blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "http://kunshou.cn99.com/"
title = "kunshou blog"
years = [ 2007 ]

[[websites]]
url   = "https://web.archive.org/web/http://www.kunshou.net/"
title = "Kunshou Blog"
years = [ 2008 ]
