display = "Laura’s Notebook"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://laura.popokatea.co.uk/"
title = "Laura’s Notebook"
years = [ 2008 ]
