display = "Len"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://len.ebumna.net/"
title = "Len"
years = [ 2006 ]
