display = "Léonie (Tink) Watson"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://www.tink.co.uk/"
title = "Léonie (Tink) Watson"
years = [ 2006 ]
