display = "Les infos d'abord"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://jesavaispas.free.fr/"
title = "Les infos d&#39;abord"
years = [ 2008 ]
