display = "LexaT"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://lexat.org/"
title = "LexaT"
years = [ 2009 ]
