display = "LibrarySupportStaff.org"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.librarysupportstaff.org/"
title = "LibrarySupportStaff.org"
years = [ 2007 ]
