display = "Lieferservice"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.foodo.de/"
title = "Lieferservice"
years = [ 2008 ]
