display = "Liskl"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://spinhex.sytes.net/"
title = "Liskl"
years = [ 2006 ]
