display = "LiveGraphics design"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://livegraphics.eu/"
title = "LiveGraphics design"
years = [ 2009 ]
