display = "LKS Prime Food Brda Przechlewo"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://2ba.gsi.pl/"
title = "LKS Prime Food Brda Przechlewo"
years = [ 2007 ]
