display = "Logism.net"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.logism.net/"
title = "Logism.net"
years = [ 2007 ]
