display = "LOLBostons"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.lolbostons.com/"
title = "LOLBostons"
years = [ 2008 ]
