display = "Lu Torrefranca"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.digitalbonsai.com/"
title = "Lu Torrefranca"
years = [ 2006 ]
