display = "Luca"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://demoniacnet.altervista.org/"
title = "Luca"
years = [ 2006 ]
