display = "Lucky Sneaks"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://luckysneaks.com/"
title = "Lucky Sneaks"
years = [ 2008 ]
