display = "lustrious.net"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://lustrious.net/"
title = "lustrious.net"
years = [ 2007 ]
