display = "Luxiano…"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.luxiano.com.ar/"
title = "Luxiano…"
years = [ 2009 ]
