display = "Macadelic"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.macadelic.de/"
title = "Macadelic"
years = [ 2009 ]
