display = "Mads Kjaer"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.madskjaer.dk/"
title = "Mads Kjaer"
years = [ 2007 ]
