display = "Mario Raudsepp"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.nanoweb.pri.ee/"
title = "Mario Raudsepp"
years = [ 2007 ]
