display = "Mark Seymour"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://hidden.shadeddarkness.net/"
title = "Mark Seymour"
years = [ 2006 ]
