display = "Martin Sarsini"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://sarsini.it/"
years = [ 2008 ]


[[websites]]
url   = "https://www.apphancer.com/"
years = [ 2023 ]
