display = "Martin"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.tankedup-imaging.com/"
title = "Martin"
years = [ 2006 ]
