display = "Matemáticas"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.aulademate.com/"
title = "Matemáticas"
years = [ 2008 ]
