display = "Mathie"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://woss.name/"
title = "Mathie"
years = [ 2006 ]
