display = "Mattia Richetto . it"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.mattiarichetto.it/"
title = "Mattia Richetto . it"
years = [ 2007 ]
