display = "Me, Myself and Mayvelous"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.mayvelous.com/"
title = "Me, Myself and Mayvelous"
years = [ 2007 ]
