display = "Medicine"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://nynik.ru/"
title = "Medicine"
years = [ 2009 ]
