display = "Mega Tokio (Vesa Piittinen)"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.megatokio.com/"
title = "Mega Tokio (Vesa Piittinen)"
years = [ 2006 ]
