display = "Megafiles.ru"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.megafiles.ru/"
title = "Megafiles.ru"
years = [ 2008 ]
