display = "Menorca web"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.menorcaon.com/"
title = "Menorca web"
years = [ 2008 ]
