display = "MG55 Web"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.mg55.net/"
title = "MG55 Web"
years = [ 2008 ]
