display = "Michał Baryś Webdeveloper"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://barys.net/"
title = "Michał Baryś Webdeveloper"
years = [ 2008 ]

[[websites]]
url   = "http://michalbarys.pl/"
title = "Michał Baryś Webdeveloper"
years = [ 2009 ]
