display = "Miles Barger"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://journal.milesbarger.com/"
title = "Miles Barger"
years = [ 2008 ]
