display = "minizen"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.minizen.net/"
title = "minizen"
years = [ 2007 ]
