display = "mirc"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.mirc.in/"
title = "mirc"
years = [ 2008 ]
