display = "missmac.net"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.missmac.net/"
title = "missmac.net"
years = [
	2007,
	2008 
]
