display = "Miyuato"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.miyuato.com/"
title = "Miyuato"
years = [ 2009 ]
