display = "MOAR PYLONS?!"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://4str4stam.net/moarpylons/"
title = "MOAR PYLONS?!"
years = [ 2008 ]
