display = "Moscowspeaks.ru"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://moscowspeaks.ru"
title = "Moscowspeaks.ru"
years = [ 2009 ]
