display = "Nadja"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.calm-n-easy.de/"
title = "Nadja"
years = [ 2006 ]
