display = "nebelseetal"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.nebelsetal.de/"
title = "nebelseetal"
years = [ 2009 ]
