display = "Nettvint.net"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.nettvint.net/"
title = "Nettvint.net"
years = [ 2007 ]
