display = "Невропатолог"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://wwwneurologist.ru/"
title = "Невропатолог"
years = [ 2009 ]
