display = "NG Life"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.gary711.net/"
title = "NG Life"
years = [ 2008 ]
