display = "Nick"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://deblog.us.to/"
title = "Nick"
years = [ 2006 ]
