display = "niqui merret"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://niquimerret.com/"
title = "niqui merret"
years = [ 2007 ]
