display = "Nonsensor: Mike Propst’s Blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.nonsensor.com/"
title = "Nonsensor: Mike Propst’s Blog"
years = [ 2007 ]
