display = "O Sofá Verde"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://sofaverde.fabrica021.com/"
title = "O Sofá Verde"
years = [ 2007 ]
