display = "Okeimakei"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://okeimakei.bitacoras.com/"
title = "Okeimakei"
years = [ 2006 ]
