display = "Otháner Kasiyas"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.othanerkasiyas.com"
title = "Otháner Kasiyas"
years = [ 2008 ]
