display = "pairacyDotCom"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.pairacy.com/"
title = "pairacyDotCom"
years = [ 2008 ]
