display = "Pandasaur"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://pandasaur.co.uk/"
title = "Pandasaur"
years = [ 2008 ]
