display = "Paper Wings"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://main.paper-wings.com/"
title = "Paper Wings"
years = [ 2007 ]
