display = "Parmon"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.devfreak.com/"
title = "Parmon"
years = [ 2006 ]
