display = "Patrick"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.thteong.com/"
years = [ 2006 ]
