display = "Patriot Goose"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://patriotgoose.com/"
title = "Patriot Goose"
years = [ 2008 ]
