display = "paulmichaelsmith.blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.paulmichaelsmith.com/blog/"
title = "paulmichaelsmith.blog"
years = [ 2007 ]
