display = "Paul Vanderschot"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.nextstepwebpages.com/"
title = "Paul Vanderschot"
years = [ 2007 ]
