display = "Phixarmedia"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.phixarmedia.com/"
title = "Phixarmedia"
years = [ 2009 ]
