display = "Pi"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://beats2.pinewave.tw/"
title = "Pi"
years = [ 2009 ]
