display = "Pilmore, Lee"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.pilmore.co.uk"
title = "Pilmore, Lee"
years = [ 2007 ]
