display = "Pixelpanzer"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.pixelpanzer.de/"
title = "Pixelpanzer"
years = [ 2008 ]
