display = "Pixel Behavior"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://www.pixelbehavior.com/"
title = "Pixel Behavior"
years = [ 2009 ]
