display = "Plokodelika"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://plokodelika.com/"
title = "Plokodelika"
years = [ 2008 ]
