display = "Pni"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://skrubu.net/"
title = "Pni"
years = [ 2006 ]
