display = "PSB-Subcom Timer info page"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://psbs.no-ip.info/"
title = "PSB-Subcom Timer info page"
years = [ 2007 ]
