display = "punkid"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.punkid.cn/"
title = "punkid"
years = [ 2007 ]
