display = "Quasarkitten.net"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.quasarkitten.net/"
title = "Quasarkitten.net"
years = [ 2009 ]
