display = "Quorum Collective"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://qsense.org/"
title = "Quorum Collective"
years = [ 2009 ]
