display = "rarefaction.co.uk"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.jsworld.co.uk/rarefaction"
title = "rarefaction.co.uk"
years = [ 2007 ]
