display = "Red Bridge Software"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.redbridgesoft.com/"
title = "Red Bridge Software"
years = [ 2008 ]
