display = "Ree’s musings"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://ree.tabulas.com/"
title = "Ree’s musings"
years = [ 2008 ]
