display = "Reelgeek"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "http://reelgeek.com/"
title = "reelgeek"
years = [ 2008 ]

[[websites]]
url   = "https://web.archive.org/web/http://www.reeelgeek.com/"
title = "Reelgeek"
years = [ 2009 ]
