display = "Rejsy antarktyda"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://alcotours.com.pl/"
title = "Rejsy antarktyda"
years = [ 2008 ]
