display = "Renan Gonçalves’s Blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.renangoncalves.com/"
title = "Renan Gonçalves’s Blog"
years = [ 2009 ]
