display = "Ricardo L"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://peace.mine.nu/"
title = "Ricardo L"
years = [ 2006 ]
