display = "Richard"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://nostrich.net/"
title = "Richard"
years = [ 2006 ]
