display = "Robert Kuykendall (appleswitch)"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.appleswitch.com/"
title = "Robert Kuykendall (appleswitch)"
years = [
	2008,
	2009 
]
