display = "Robert Bue"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.komplekser.net/"
title = "Robert Bue"
years = [ 2007 ]
