display = "Samuel “Artoo” Goodwin"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.freshman-15.blogspot.com/"
title = "Samuel “Artoo” Goodwin"
years = [ 2006 ]
