display = "Sandra Clark"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.shayna.com/"
title = "Sandra Clark"
years = [ 2007 ]
