display = "Schwackages!"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.schwackages.com/"
title = "Schwackages!"
years = [ 2007 ]
