display = "SCV君"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://scvlife.egloos.com/"
title = "SCV君"
years = [ 2008 ]
