display = "Seraphyn Blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://seraphyn.deveth.org/"
title = "Seraphyn Blog"
years = [ 2009 ]
