display = "sewmyheadon.com"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://sewmyheadon.com/"
title = "sewmyheadon.com"
years = [ 2008 ]
