display = "Sexy babes to stuzz"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://wwwstuzzico.com/"
title = "Sexy babes to stuzz"
years = [ 2008 ]
