display = "Sexy Plus Size Lingerie"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://www.myfavoritelingerie.com/"
title = "Sexy Plus Size Lingerie"
years = [ 2007 ]
