display = "Shaunec.com"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.shaunec.com/"
title = "Shaunec.com"
years = [ 2008 ]
