display = "Shining Summer Days…"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://karol.ubbcn.com/blog"
title = "Shining Summer Days…"
years = [ 2007 ]
