display = "Shoegazer"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.shoegazer.cn/"
title = "Shoegazer"
years = [ 2007 ]
