display = "Shoppa"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.shop-online.se/"
title = "Shoppa"
years = [ 2008 ]
