display = "shpyo"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.shpyo.net/"
title = "shpyo"
years = [ 2007 ]
