display = "Sieťook"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://sietook.org/"
title = "Sieťook"
years = [ 2007 ]
