display = "Simon Willison"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://simon.incutio.com/"
title = "Simon Willison"
years = [ 2006 ]
