display = "Skeptikal.org"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://skeptikal.org/"
title = "Skeptikal.org"
years = [ 2009 ]
