display = "Skimboard"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.skimboard.se/"
title = "Skimboard"
years = [ 2009 ]
