display = "slice2css"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.slice2css.com/"
title = "slice2css"
years = [ 2008 ]
