display = "SmilingJ code&more"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://blog.smilingj.net/"
title = "SmilingJ code&amp;more"
years = [ 2008 ]
