display = "SopRanos..!!"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://sopranos.tistory.com/"
title = "SopRanos..!!"
years = [ 2008 ]
