display = "Southern Media"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.southernmedia.org/"
title = "Southern Media"
years = [ 2008 ]
