display = "Splash of Style"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.splashofstyle.com/"
title = "Splash of Style"
years = [ 2007 ]
