display = "Spravodaj.madaj.net"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://spravodaj.madaj.net/"
title = "Spravodaj.madaj.net"
years = [ 2007 ]
