display = "stefan.waidele.info"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://stefan.waidele.info/"
title = "stefan.waidele.info"
years = [ 2009 ]
