display = "Stefan Von Dollen"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://www.vondollens.us/"
title = "Stefan Von Dollen"
years = [ 2006 ]
