display = "Strelban’s Blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.blog.strelban.net/"
title = "Strelban’s Blog"
years = [ 2008 ]
