display = "Supermumin"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://supermumin.net/"
title = "Supermumin"
years = [
	2007,
	2008,
	2009 
]
