display = "Sutekidane"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.sutekidane.net/blog/"
title = "Sutekidane"
years = [ 2007 ]
