display = "Swizzle Designs"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://www.swizzledesigns.com/"
title = "Swizzle Designs"
years = [ 2008 ]
