display = "T_T======="

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.tetst.com/"
title = "T_T======="
years = [ 2007 ]
