display = "Talk is cheap…"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://arda.pardusman.org/blog/"
title = "Talk is cheap…"
years = [ 2007 ]
