display = "Tania Sodré"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.taniasodre.com/"
title = "Tania Sodré"
years = [ 2007 ]
