display = "Tech Wizard"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.coolwizardz.com/"
title = "Tech Wizard"
years = [ 2008 ]
