display = "Teflonminne"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://drf.teflonminne.se/"
title = "Teflonminne"
years = [ 2008 ]
