display = "tgfoo.com"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.tgfoo.com/"
title = "tgfoo.com"
years = [ 2009 ]
