display = "The Fraggle"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://www.dailyfraggle.de/"
title = "The Fraggle"
years = [ 2006 ]
