display = "The Place is Dead (Ronnie Brown)"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.thisplaceisdead.com/"
title = "The Place is Dead (Ronnie Brown)"
years = [ 2006 ]
