display = "The personal blog of Phill Nacelli."

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.phillnacelli.net/"
title = "The personal blog of Phill Nacelli."
years = [ 2009 ]
