display = "The Naked Truth (N. Mallory)"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://nmallory.exit-23.net/"
title = "The Naked Truth (N. Mallory)"
years = [ 2006 ]
