display = "The Web Blog of Alex Fraiser"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://alexfraiser.com/"
title = "The Web Blog of Alex Fraiser"
years = [ 2008 ]
