display = "The Rec"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://wdupe.j0ker.net/"
title = "The Rec"
years = [ 2006 ]
