display = "Tim’s Bits and Pieces"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://bur.st/~timp/"
title = "Tim’s Bits and Pieces"
years = [ 2008 ]
