display = "Tinta Fantasma"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://tintafantasma.net/"
title = "Tinta Fantasma"
years = [ 2007 ]
