display = "To Infinity"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.inexistent.org/"
title = "To Infinity"
years = [ 2008 ]
