display = "todoslot"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.todoslot.es/"
title = "todoslot"
years = [ 2008 ]
