display = "Tommy’s Blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.licns.com/"
title = "Tommy’s Blog"
years = [ 2007 ]
