display = "toob"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://toob.no/"
title = "toob"
years = [ 2008 ]
