display = "tsuki story"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://tsuki.zc.bz/blog"
title = "tsuki story"
years = [ 2007 ]
