display = "Twisted Intellect"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://twistedintellect.com/"
title = "Twisted Intellect"
years = [
	2006,
	2007,
	2008 
]
