display = "Typecho"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.typecho.net/"
title = "Typecho"
years = [ 2009 ]
