display = "UITest.com"

# TODO: Either update with information in jens-meiert.toml and remove entries there, or move to jens-meiert.toml

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://frontenddogma.com/?uitest.com"
title = "UITest.com"
years = [ 2006 ]
