display = "Uninstallme"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://uninstallme.com/"
title = "Uninstallme"
years = [ 2009 ]
