display = "Uros Gruber"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.gruber.si/"
title = "Uros Gruber"
years = [ 2008 ]
