display = "Веб-разработчик"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2007/http://dyatko.ru/"
title = "Веб-разработчик"
years = [ 2008 ]
