display = "Velmont – Odin Hørthe Omdal"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://velmont.net/"
title = "Velmont – Odin Hørthe Omdal"
years = [ 2007 ]
