display = "Vernon Trevor Gerzen-Personal Portfolio"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.vernontgerzen.com/"
title = "Vernon Trevor Gerzen-Personal Portfolio"
years = [ 2008 ]
