display = "Versicherung"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.ca-versicherung.at/"
title = "Versicherung"
years = [ 2009 ]
