display = "Viasto"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://viasto.net/"
title = "Viasto"
years = [ 2007 ]
