display = "Вконтакте"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://vkontakte.ru/"
title = "Вконтакте"
years = [ 2008 ]
