display = "W"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.wision.ch/blog/"
title = "W"
years = [ 2006 ]
