display = "wachuwachu"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.wachuwachu.com/"
title = "wachuwachu"
years = [ 2007 ]
