display = "Weavery Swing"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://ginalan.com/blog/"
title = "Weavery Swing"
years = [ 2007 ]
