display = "Web Designer Heine Jensvold"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "http://web.archive.org/web/20071026125526/http://heine.tagg.no:80/"
title = "Web Designer Heine Jensvold"
years = [ 2008 ]
