display = "Web Car Mag"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://webcarmag.ifastnet.com/"
title = "Web Car Mag"
years = [ 2007 ]
