display = "WebDesign"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.webdesign-in.de/"
title = "WebDesign"
years = [ 2008 ]
