display = "WeBlog de JoEyInBoX"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.joeyinbox.net/"
title = "WeBlog de JoEyInBoX"
years = [ 2007 ]
