display = "WebScriptz"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.webscriptz.net/"
title = "WebScriptz"
years = [ 2008 ]
