display = "WENBOlog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2006/http://bolog.blog.com.cn/"
title = "WENBOlog"
years = [ 2007 ]
