display = "White’s Blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://white.addoma.de/s9y"
title = "White’s Blog"
years = [ 2009 ]
