display = "Whydoyouwork"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.whydoyouwork.com/"
title = "Whydoyouwork"
years = [ 2007 ]
