display = "With Story (Astraea)"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2005/http://withstory.net/"
title = "With Story (Astraea)"
years = [ 2006 ]
