display = "WWW:P"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://wwwp.si/"
title = "WWW:P"
years = [ 2009 ]
