display = "Xavier Muñiz’s blog"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://xmz.com.mx/"
title = "Xavier Muñiz’s blog"
years = [ 2008 ]
