display = "Xtoph"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://zeus.fh-brandenburg.de/~franzc/blog/"
title = "Xtoph"
years = [ 2006 ]
