display = "zone41"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://zone41.info/"
title = "zone41"
years = [ 2008 ]
