display = "写一点"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.xieyidian.com/"
title = "写一点"
years = [ 2009 ]
