display = "媒体在线"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.mediaol.cn/"
title = "媒体在线"
years = [ 2007 ]
