display = "安化论坛"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.anhua.org/"
title = "安化论坛"
years = [ 2009 ]
