display = "欧洲旅游"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.17ouzhou.com/"
title = "欧洲旅游"
years = [ 2007 ]
