display = "毅博客"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://andymao.com/andy/"
title = "毅博客"
years = [ 2007 ]
