display = "海南旅游网"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/2008/http://www.ethainan.com/"
title = "海南旅游网"
years = [ 2009 ]
