display = "闲耘.博客"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://blog.xianyun.org/"
title = "闲耘.博客"
years = [ 2009 ]
