display = "촌티? 촌티!"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://chonty.tistory.com/"
title = "촌티? 촌티!"
years = [ 2008 ]
